//11
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.2.0.11")]
[assembly: AssemblyVersion("1.2.0.0")]
[assembly: AssemblyInformationalVersion("v1.2.0")]
[assembly: KSPAssembly("SafetyWall", 1,2,0)]

namespace SafetyWall
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 2;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "1.2.0.0";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}